## Transforming datasets

In [31]:
import pandas as pd
import os

In [42]:
# pull extracted table
players_per_game = pd.read_json('../Extract/Resources/player_per_game_stats.json')
players_per_game.head(10)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Steven Adams,C,26.0,OKC,63.0,63.0,26.7,4.5,7.6,.592,...,.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
1,Bam Adebayo,PF,22.0,MIA,72.0,72.0,33.6,6.1,11.0,.557,...,.691,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9
2,LaMarcus Aldridge,C,34.0,SAS,53.0,53.0,33.1,7.4,15.0,.493,...,.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,Kyle Alexander,C,23.0,MIA,2.0,0.0,6.5,0.5,1.0,.500,...,,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0
4,Nickeil Alexander-Walker,SG,21.0,NOP,47.0,1.0,12.6,2.1,5.7,.368,...,.676,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7
5,Grayson Allen,SG,24.0,MEM,38.0,0.0,18.9,3.1,6.6,.466,...,.867,0.2,2.0,2.2,1.4,0.3,0.1,0.9,1.4,8.7
6,Jarrett Allen,C,21.0,BRK,70.0,64.0,26.5,4.3,6.6,.649,...,.633,3.1,6.5,9.6,1.6,0.6,1.3,1.1,2.3,11.1
7,Kadeem Allen,PG,27.0,NYK,10.0,0.0,11.7,1.9,4.4,.432,...,.636,0.2,0.7,0.9,2.1,0.5,0.2,0.8,0.7,5.0
8,Al-Farouq Aminu,PF,29.0,ORL,18.0,2.0,21.1,1.4,4.8,.291,...,.655,1.3,3.5,4.8,1.2,1.0,0.4,0.9,1.5,4.3
9,Justin Anderson,SG,26.0,BRK,10.0,1.0,10.7,1.0,3.8,.263,...,.500,0.1,2.0,2.1,0.8,0.0,0.6,0.4,1.3,2.8

In [58]:
# get and check the column names and dtypes
players_per_game.dtypes

Player     object
Pos        object
Age       float64
Tm         object
G         float64
GS        float64
MP        float64
FG        float64
FGA       float64
FG%        object
3P        float64
3PA       float64
3P%        object
2P        float64
2PA       float64
2P%        object
eFG%       object
FT        float64
FTA       float64
FT%        object
ORB       float64
DRB       float64
TRB       float64
AST       float64
STL       float64
BLK       float64
TOV       float64
PF        float64
PTS       float64
dtype: object

In [77]:
# Check to see if there are any rows with missing data
players_per_game.count()

Player    651
Pos       651
Age       651
Tm        651
G         651
GS        651
MP        651
FG        651
FGA       651
FG%       651
3P        651
3PA       651
3P%       651
2P        651
2PA       651
2P%       651
eFG%      651
FT        651
FTA       651
FT%       651
ORB       651
DRB       651
TRB       651
AST       651
STL       651
BLK       651
TOV       651
PF        651
PTS       651
dtype: int64

In [81]:
# get the team abbbreviations
count_tm = players_per_game['Tm'].value_counts()
count_tm

TOT    60
MIN    24
BRK    24
SAC    23
WAS    23
DET    22
GSW    22
ATL    21
MEM    21
HOU    21
CLE    21
MIA    21
DEN    21
UTA    20
LAC    20
LAL    20
PHO    19
ORL    19
POR    19
PHI    19
DAL    19
TOR    18
OKC    18
SAS    18
BOS    17
IND    17
CHI    17
MIL    17
NYK    17
NOP    17
CHO    16
Name: Tm, dtype: int64