In [1]:
import pymongo
import pandas as pd
import json
from sqlalchemy import create_engine

In [8]:
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

In [9]:
db = client['Project']
collection = db['Player_info']

In [11]:
pStats = pd.read_csv('../Transform/clean_data/Player_Info.csv')
pStats

,Unnamed: 0,PLAYER,POS,HEIGHT,WEIGHT,BIRTH_DATE,NATIONALITY,EXPERIENCE,COLLEGE
0,0,DeAndre' Bembry,SG,6-5,210,773280000000,US,3,Saint Joseph's
1,1,Charlie Brown,SG,6-6,199,854841600000,US,R,Saint Joseph's
2,2,Vince Carter,PF,6-6,220,223084800000,US,21,UNC
3,3,John Collins,PF,6-9,235,874972800000,US,2,Wake Forest
4,4,Bruno Fernando,C,6-9,240,903139200000,AO,R,Maryland
...,...,...,...,...,...,...,...,...,...
525,525,Ish Smith,PG,6-0,175,584064000000,US,9,Wake Forest
526,526,Isaiah Thomas,PG,5-9,185,602812800000,US,8,Washington
527,527,Jarrod Uthoff,PF,6-9,221,737769600000,US,1,Iowa
528,528,Moritz Wagner,C,6-11,245,862012800000,DE,1,Michigan
529,529,Johnathan Williams,PF,6-9,228,801100800000,US,1,"Missouri, Gonzaga"

In [12]:
player_info_dict = pStats.to_dict("Players")
collection.insert_many(player_info_dict)

ValueError: orient 'Players' not understood

In [2]:
connection_string = "postgres:postgres@localhost:5432/customer_db"
engine = create_engine(f'postgresql://{connection_string}')

In [ ]:
# Confirm tables
engine.table_names()